In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
from datetime import datetime, timedelta, UTC
import matplotlib.pyplot as plt
import numpy as np

df= pd.read_csv('/content/ONINE_FOOD_DELIVERY_ANALYSIS.csv')
df

,Order_ID,Customer_ID,Customer_Age,Customer_Gender,City,Area,Restaurant_ID,Restaurant_Name,Cuisine_Type,Order_Date,...,Final_Amount,Payment_Mode,Order_Status,Cancellation_Reason,Delivery_Partner_ID,Delivery_Rating,Restaurant_Rating,Order_Day,Peak_Hour,Profit_Margin
0,ORD000001,CUST6948,19.0,Male,NaN,Central,RES936,Restaurant_29,Chinese,10/20/2024,...,NaN,UPI,Delivered,NaN,DP563,5.0,4.4,Weekend,True,0.13
1,ORD000002,CUST6515,NaN,Female,Chennai,North,RES689,Restaurant_419,Chinese,08-12-2024,...,4849.0,COD,Delivered,NaN,DP369,5.0,4.7,Weekday,True,0.48
2,ORD000003,CUST1765,NaN,Male,Delhi,NaN,RES723,Restaurant_244,Arabian,12-08-2024,...,737.0,Wallet,Delivered,NaN,DP580,4.0,4.9,Weekend,True,0.08
3,ORD000004,CUST2744,NaN,Male,Mumbai,Central,RES951,Restaurant_178,Chinese,10-08-2024,...,NaN,UPI,Cancelled,Late Delivery,DP155,2.0,3.4,Weekday,NaN,0.04
4,ORD000005,CUST4389,57.0,Female,Chennai,South,RES419,Restaurant_262,Chinese,02-04-2024,...,352.0,Card,Delivered,NaN,DP728,2.0,4.4,Weekend,False,0.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,ORD099996,CUST3722,NaN,NaN,Mumbai,NaN,RES295,Restaurant_500,Arabian,06-10-2024,...,132.0,Card,Delivered,NaN,DP835,2.0,4.0,Weekday,True,0.17
99996,ORD099997,CUST6158,NaN,Male,Mumbai,East,RES157,Restaurant_458,Arabian,4/22/2024,...,1078.0,NaN,Delivered,NaN,DP476,4.0,3.5,Weekday,False,-0.15
99997,ORD099998,CUST2155,NaN,NaN,Delhi,East,RES287,Restaurant_273,NaN,2/23/2024,...,NaN,COD,Cancelled,NaN,DP577,2.0,4.0,Weekday,True,0.47
99998,ORD099999,CUST3015,NaN,Female,Delhi,North,RES491,Restaurant_241,NaN,12-10-2024,...,NaN,NaN,Delivered,NaN,DP896,NaN,4.3,Weekday,NaN,0.44
99999,ORD100000,CUST7959,NaN,Other,Hyderabad,East,RES680,Restaurant_237,Chinese,NaN,...,NaN,Wallet,Cancelled,NaN,DP908,5.0,4.2,Weekday,False,0.20

In [ ]:
df.info()
#df.dtypes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 25 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Order_ID             100000 non-null  object
 1   Customer_ID          100000 non-null  object
 2   Customer_Age         49907 non-null   float64
 3   Customer_Gender      75144 non-null   object
 4   City                 83274 non-null   object
 5   Area                 83315 non-null   object
 6   Restaurant_ID        100000 non-null  object
 7   Restaurant_Name      100000 non-null  object
 8   Cuisine_Type         83115 non-null   object
 9   Order_Date           98986 non-null   object
 10  Order_Time           98002 non-null   object
 11  Delivery_Time_Min    66641 non-null   float64
 12  Distance_km          66530 non-null   float64
 13  Order_Value          66673 non-null   float64
 14  Discount_Applied     83285 non-null   float64
 15  Final_Amount         44303 non-null   float64
 16  Payment_Mode         80089 non-null   object
 17  Order_Status         100000 non-null  object
 18  Cancellation_Reason  9031 non-null    object
 19  Delivery_Partner_ID  100000 non-null  object
 20  Delivery_Rating      83477 non-null   float64
 21  Restaurant_Rating    100000 non-null  float64
 22  Order_Day            100000 non-null  object
 23  Peak_Hour            67038 non-null   object
 24  Profit_Margin        100000 non-null  float64
dtypes: float64(9), object(16)
memory usage: 19.1+ MB

**Data Cleaning Process**

In [ ]:
missing_values = df.isnull().sum()
print("Missing Values:")
print(missing_values)
df

Missing Values:
Order_ID                   0
Customer_ID                0
Customer_Age           50093
Customer_Gender        24856
City                   16726
Area                   16685
Restaurant_ID              0
Restaurant_Name            0
Cuisine_Type           16885
Order_Date              1014
Order_Time              1998
Delivery_Time_Min      33359
Distance_km            33470
Order_Value            33327
Discount_Applied       16715
Final_Amount           55697
Payment_Mode           19911
Order_Status               0
Cancellation_Reason    90969
Delivery_Partner_ID        0
Delivery_Rating        16523
Restaurant_Rating          0
Order_Day                  0
Peak_Hour              32962
Profit_Margin              0
dtype: int64

,Order_ID,Customer_ID,Customer_Age,Customer_Gender,City,Area,Restaurant_ID,Restaurant_Name,Cuisine_Type,Order_Date,...,Final_Amount,Payment_Mode,Order_Status,Cancellation_Reason,Delivery_Partner_ID,Delivery_Rating,Restaurant_Rating,Order_Day,Peak_Hour,Profit_Margin
0,ORD000001,CUST6948,19.0,Male,NaN,Central,RES936,Restaurant_29,Chinese,10/20/2024,...,NaN,UPI,Delivered,NaN,DP563,5.0,4.4,Weekend,True,0.13
1,ORD000002,CUST6515,NaN,Female,Chennai,North,RES689,Restaurant_419,Chinese,08-12-2024,...,4849.0,COD,Delivered,NaN,DP369,5.0,4.7,Weekday,True,0.48
2,ORD000003,CUST1765,NaN,Male,Delhi,NaN,RES723,Restaurant_244,Arabian,12-08-2024,...,737.0,Wallet,Delivered,NaN,DP580,4.0,4.9,Weekend,True,0.08
3,ORD000004,CUST2744,NaN,Male,Mumbai,Central,RES951,Restaurant_178,Chinese,10-08-2024,...,NaN,UPI,Cancelled,Late Delivery,DP155,2.0,3.4,Weekday,NaN,0.04
4,ORD000005,CUST4389,57.0,Female,Chennai,South,RES419,Restaurant_262,Chinese,02-04-2024,...,352.0,Card,Delivered,NaN,DP728,2.0,4.4,Weekend,False,0.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,ORD099996,CUST3722,NaN,NaN,Mumbai,NaN,RES295,Restaurant_500,Arabian,06-10-2024,...,132.0,Card,Delivered,NaN,DP835,2.0,4.0,Weekday,True,0.17
99996,ORD099997,CUST6158,NaN,Male,Mumbai,East,RES157,Restaurant_458,Arabian,4/22/2024,...,1078.0,NaN,Delivered,NaN,DP476,4.0,3.5,Weekday,False,-0.15
99997,ORD099998,CUST2155,NaN,NaN,Delhi,East,RES287,Restaurant_273,NaN,2/23/2024,...,NaN,COD,Cancelled,NaN,DP577,2.0,4.0,Weekday,True,0.47
99998,ORD099999,CUST3015,NaN,Female,Delhi,North,RES491,Restaurant_241,NaN,12-10-2024,...,NaN,NaN,Delivered,NaN,DP896,NaN,4.3,Weekday,NaN,0.44
99999,ORD100000,CUST7959,NaN,Other,Hyderabad,East,RES680,Restaurant_237,Chinese,NaN,...,NaN,Wallet,Cancelled,NaN,DP908,5.0,4.2,Weekday,False,0.20

In [ ]:
import numpy as np

# Pre-process 'Peak_Hour': Treat 0.0 as a missing value and impute with mode
# First, standardize '0.0' to np.nan to prepare for mode imputation
#df['Peak_Hour'] = df['Peak_Hour'].replace({0.0: np.nan, '0.0': np.nan})

# Get the mode of the non-NaN Peak_Hour values (True/False)
# .mode()[0] is used to get the actual value, as mode() returns a Series
#peak_hour_mode = df['Peak_Hour'].mode()[0]

# Fill the NaN values with the calculated mode
#df['Peak_Hour'] = df['Peak_Hour'].fillna(peak_hour_mode)

# Finally, ensure the column is of boolean type
#df['Peak_Hour'] = df['Peak_Hour'].astype(bool)

# 1. Handle Categorical Constants (Cancellation Reason)
# We assume missing values mean the order was NOT cancelled.
df['Cancellation_Reason'] = df['Cancellation_Reason'].fillna('None')

# 2. Handle Numerical Imputation (Median)
# Using median for columns with outliers like Age, Distance, and Time
numerical_cols = ['Customer_Age', 'Delivery_Time_Min', 'Distance_km', 'Order_Value']
for col in numerical_cols:
    df[col] = df[col].fillna(df[col].median())

# 3. Handle Categorical Imputation (Mode)
# Filling with the most frequent value for labels
#categorical_cols = ['Customer_Gender', 'City', 'Area', 'Cuisine_Type', 'Payment_Mode', 'Peak_Hour'] # Peak_Hour is handled separately now
#for col in categorical_cols:
#   df[col] = df[col].fillna(df[col].mode()[0])

    # 3. Handle Categorical Imputation (Mode)
# Defining categorical columns based on your dataset headers
categorical_cols = ['Customer_Gender', 'City', 'Area', 'Cuisine_Type', 'Payment_Mode', 'Peak_Hour']

for col in categorical_cols:
    # Ensure the column exists before imputing
    if col in df.columns:
        # Calculate the mode (most frequent value)
        col_mode = df[col].mode()[0]
        # Fill NaN values with the calculated mode
        df[col] = df[col].fillna(col_mode)

# Verification: Check if any NaNs remain in Peak_Hour
print(f"Remaining NaNs in Peak_Hour: {df['Peak_Hour'].isna().sum()}")

# 4. Handle Discounts and Final Amount Logic
# First, assume missing discount means 0 discount
df['Discount_Applied'] = df['Discount_Applied'].fillna(0)

# 5. Recalculate Final_Amount where missing: Final = Value - Discount
# This is more accurate than just using a median.
df['Final_Amount'] = df['Final_Amount'].fillna(df['Order_Value'] - df['Discount_Applied'])

# If any Final_Amount are still missing (due to missing Order_Value), use median
df['Final_Amount'] = df['Final_Amount'].fillna(df['Final_Amount'].median())

# 6. Handle Ratings
# We can use a neutral rating of 3.0 or the median for missing delivery ratings
df['Delivery_Rating'] = df['Delivery_Rating'].fillna(df['Delivery_Rating'].median())

# 7. Handle Time/Date (Forward Fill)
# If the data is chronological, filling from the previous row is best
df['Order_Date'] = df['Order_Date'].fillna(method='ffill')
df['Order_Time'] = df['Order_Time'].fillna(method='ffill')

# 8. Verify the results
print("Missing values after cleaning:")
print(df.isnull().sum())

/tmp/ipython-input-515/569302231.py:43: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(col_mode)
/tmp/ipython-input-515/569302231.py:65: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Order_Date'] = df['Order_Date'].fillna(method='ffill')
/tmp/ipython-input-515/569302231.py:66: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Order_Time'] = df['Order_Time'].fillna(method='ffill')

Remaining NaNs in Peak_Hour: 0
Missing values after cleaning:
Order_ID               0
Customer_ID            0
Customer_Age           0
Customer_Gender        0
City                   0
Area                   0
Restaurant_ID          0
Restaurant_Name        0
Cuisine_Type           0
Order_Date             0
Order_Time             0
Delivery_Time_Min      0
Distance_km            0
Order_Value            0
Discount_Applied       0
Final_Amount           0
Payment_Mode           0
Order_Status           0
Cancellation_Reason    0
Delivery_Partner_ID    0
Delivery_Rating        0
Restaurant_Rating      0
Order_Day              0
Peak_Hour              0
Profit_Margin          0
dtype: int64

df.duplicated().sum()
df['Peak_Hour'].value_counts()

In [ ]:
df.duplicated().sum()
df

,Order_ID,Customer_ID,Customer_Age,Customer_Gender,City,Area,Restaurant_ID,Restaurant_Name,Cuisine_Type,Order_Date,...,Final_Amount,Payment_Mode,Order_Status,Cancellation_Reason,Delivery_Partner_ID,Delivery_Rating,Restaurant_Rating,Order_Day,Peak_Hour,Profit_Margin
0,ORD000001,CUST6948,19.0,Male,Hyderabad,Central,RES936,Restaurant_29,Chinese,10/20/2024,...,1197.0,UPI,Delivered,None,DP563,5.0,4.4,Weekend,True,0.13
1,ORD000002,CUST6515,39.0,Female,Chennai,North,RES689,Restaurant_419,Chinese,08-12-2024,...,4849.0,COD,Delivered,None,DP369,5.0,4.7,Weekday,True,0.48
2,ORD000003,CUST1765,39.0,Male,Delhi,South,RES723,Restaurant_244,Arabian,12-08-2024,...,737.0,Wallet,Delivered,None,DP580,4.0,4.9,Weekend,True,0.08
3,ORD000004,CUST2744,39.0,Male,Mumbai,Central,RES951,Restaurant_178,Chinese,10-08-2024,...,1197.0,UPI,Cancelled,Late Delivery,DP155,2.0,3.4,Weekday,False,0.04
4,ORD000005,CUST4389,57.0,Female,Chennai,South,RES419,Restaurant_262,Chinese,02-04-2024,...,352.0,Card,Delivered,None,DP728,2.0,4.4,Weekend,False,0.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,ORD099996,CUST3722,39.0,Other,Mumbai,South,RES295,Restaurant_500,Arabian,06-10-2024,...,132.0,Card,Delivered,None,DP835,2.0,4.0,Weekday,True,0.17
99996,ORD099997,CUST6158,39.0,Male,Mumbai,East,RES157,Restaurant_458,Arabian,4/22/2024,...,1078.0,Card,Delivered,None,DP476,4.0,3.5,Weekday,False,-0.15
99997,ORD099998,CUST2155,39.0,Other,Delhi,East,RES287,Restaurant_273,Indian,2/23/2024,...,1177.0,COD,Cancelled,None,DP577,2.0,4.0,Weekday,True,0.47
99998,ORD099999,CUST3015,39.0,Female,Delhi,North,RES491,Restaurant_241,Indian,12-10-2024,...,1097.0,Card,Delivered,None,DP896,3.0,4.3,Weekday,False,0.44
99999,ORD100000,CUST7959,39.0,Other,Hyderabad,East,RES680,Restaurant_237,Chinese,12-10-2024,...,2909.0,Wallet,Cancelled,None,DP908,5.0,4.2,Weekday,False,0.20

In [ ]:
df['Peak_Hour'].value_counts()

Peak_Hour
False    66547
True     33453
Name: count, dtype: int64

In [ ]:
# 9. Save the cleaned data
df.to_csv('cleaned_food_delivery_data.csv', index=False)